name: Python CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # --------------------
  # TEST JOB
  # --------------------
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Check files
        run: ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt

      - name: Run tests
        run: python -m pytest


  # --------------------
  # BUILD JOB
  # --------------------
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Create build directory
        run: |
          mkdir build
          cp -r src build/
          cp requirments.txt build/

      - name: Create build package
        run: |
          tar -czf python-app.tar.gz build/

      - name: Check build
        run: |
          echo "Build contents:"
          ls -lh
          ls -lh build/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: python-app.tar.gz